#!/bin/bash

# Supabase status check
echo "🔍 Checking Supabase connection..."
echo ""

export $(cat .env | grep -v '^#' | xargs)

echo "VITE_SUPABASE_URL: $VITE_SUPABASE_URL"
echo "VITE_SUPABASE_PROJECT_ID: $VITE_SUPABASE_PROJECT_ID"
echo ""
echo "✅ Environment variables loaded"
echo ""
echo "==============================================="
echo "📋 NEXT STEPS"
echo "==============================================="
echo ""
echo "1️⃣  Apply Supabase Migrations:"
echo "   One-click: https://app.supabase.com/project/kttbmxpmvmsakxfbelen/sql/new"
echo ""
echo "2️⃣  Copy and run the SQL from:"
echo "    - supabase/migrations/20260320184232_08b6f801-c7ff-45e9-b6f1-2709a71e9a7b.sql"
echo "    - supabase/migrations/20260320184244_d07abe37-0e83-4d40-b8b3-882fd7504400.sql"
echo ""
echo "3️⃣  After migration, create a test user:"
echo "    - Go to: https://app.supabase.com/project/kttbmxpmvmsakxfbelen/auth/users"
echo "    - Click 'Create a new user'"
echo "    - Email: admin@empresa.cl"
echo "    - Password: admin123"
echo ""
echo "4️⃣  Add the role:"
echo "    - Execute in Supabase SQL Editor:"
echo "    INSERT INTO user_roles (user_id, role)"
echo "    SELECT id, 'superadmin' FROM auth.users"
echo "    WHERE email = 'admin@empresa.cl';"
echo ""
echo "5️⃣  Create profile:"
echo "    INSERT INTO profiles (user_id, first_name, last_name, email, is_active)"
echo "    SELECT id, 'Carlos', 'Mendoza', email, true FROM auth.users"
echo "    WHERE email = 'admin@empresa.cl';"
echo ""
echo "==============================================="
